chore: reduced scans to one job

diff --git a/.github/workflows/trivy-scan.yaml b/.github/workflows/trivy-scan.yaml
--- a/.github/workflows/trivy-scan.yaml
+++ b/.github/workflows/trivy-scan.yaml
@@ -1,4 +1,4 @@
-# .github/workflows/security-scan.yaml
+# .github/workflows/trivy-scan.yaml
 name: Security Scan
 
 on:
@@ -27,7 +27,7 @@ on:
       issue-on-findings:
         description: 'GitHub users to assign when creating an issue for failed scans (comma-separated list: ''@user1'', ''@user2''). If left empty, no issue will be created.'
         required: false
-        default: 'false'
+        default: ''
         type: string
     secrets:
       GH_TOKEN:
@@ -41,9 +41,7 @@ env:
   TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,aquasec/trivy-db,ghcr.io/aquasecurity/trivy-db
 
 jobs:
-
-  configuration_scan:
-    if: ${{ inputs.scan-type == 'config' }}
+  security_scan:
     outputs:
       NOTIFICATION: ${{ steps.scan.outcome == 'failure' && 'true' || 'false' }}
     runs-on: ubuntu-latest
@@ -65,64 +63,9 @@ jobs:
 
     - name: setup trivy
       uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
-    
-    - name: scan configuration for full report
-      run: |
-        trivy config ${{ inputs.path }} --exit-code 0
-
-    - name: scan configuration with configured severities
-      continue-on-error: true
-      env:
-        REPORT: ${{ inputs.use-test-reporter == true && '-f json -o ./scan-results/trivy.json' || '' }}
-        IGNOREFILE: ${{ inputs.trivyignorefile != '' && format('--ignorefile {0}', inputs.trivyignorefile) || '' }}
-      id: scan
-      run: |
-        trivy config ${{ inputs.path }} \
-          --exit-code 1 \
-          --severity HIGH,CRITICAL,UNKNOWN \
-          --timeout 10m \
-          $IGNOREFILE \
-          $REPORT
-
-    - name: convert Trivy report to CTRF format
-      if: ${{ always() && inputs.use-test-reporter }}
-      run: |
-        python3 _security-tools/security-scanning/trivyconfig2ctrf.py ./scan-results/trivy.json ./scan-results/trivy.ctrf.json
-    
-    - name: Publish Test Report
-      if: ${{ always() && inputs.use-test-reporter }}
-      uses: ctrf-io/github-test-reporter@v1
-      with:
-        report-path: './scan-results/trivy.ctrf.json'
-        template-path: '_security-tools/security-scanning/config_scan_template.hbs'
-        custom-report: true
-
-  filesystem_scan:
-    if: ${{ inputs.scan-type == 'filesystem' || inputs.scan-type == '' }}
-    outputs:
-      NOTIFICATION: ${{ steps.scan.outcome == 'failure' && 'true' || 'false' }}
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: checkout repository
-      uses: actions/checkout@v4
-    
-    - name: checkout security-scanning scripts
-      uses: actions/checkout@v4
-      with:
-        repository: zweitag/github-actions
-        ref: chore--create-configurable-Security-Scan
-        path: _security-tools
-        sparse-checkout: security-scanning
-
-    - name: create output folder
-      run: mkdir -p ./scan-results
-
-    - name: setup trivy
-      uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
-
-    - name: download vulnerabilities database from aws
-      continue-on-error: true
+      
+    - name: download vulnerabilities database
+      if: inputs.scan-type != 'config'
       run: |
         MAX_RETRIES=3
         RETRY_DELAY=60
@@ -142,43 +85,56 @@ jobs:
             sleep $RETRY_DELAY
           fi
         done
-        exit 1
-
-    - name: download vulnerabilities database if aws failed
-      if: failure()
-      run: |
-        MAX_RETRIES=3
-        RETRY_DELAY=60
-        ATTEMPT=1
         
-        until [ $ATTEMPT -gt $MAX_RETRIES ]
-        do
-          echo "Attempt $ATTEMPT of $MAX_RETRIES..."
-          GITHUB_TOKEN=${{ secrets.GH_TOKEN }} trivy fs --download-db-only
+        echo "Trying fallback without custom repository..."
+        GITHUB_TOKEN=${{ secrets.GH_TOKEN }} trivy fs --download-db-only
 
-          if [ $? -eq 0 ]; then
-            echo "Trivy DB download succeeded."
-            exit 0
-          else
-            echo "Trivy DB download failed. Retrying in $RETRY_DELAY seconds..."
-            ATTEMPT=$((ATTEMPT + 1))
-            sleep $RETRY_DELAY
-          fi
-        done
-        exit 1
+    - name: scan for full report (config)
+      if: inputs.scan-type == 'config'
+      run: trivy config ${{ inputs.path }} --exit-code 0
 
-    - name: scan filesystem for full report
-      if: always()
-      run: |
-        trivy fs ${{ inputs.path }} --exit-code 0 --skip-db-update
+    - name: scan for full report (filesystem)
+      if: inputs.scan-type == 'filesystem'
+      run: trivy fs ${{ inputs.path }} --exit-code 0 --skip-db-update
 
-    # ob mit report geht weiß ich noch nicht
-    - name: scan filesystem for configured severities
-      if: always()
+    - name: scan for full report (image - filesystem)
+      if: inputs.scan-type == 'image'
+      run: trivy fs ${{ inputs.path }} --exit-code 0 --skip-db-update
+
+    - name: build docker image
+      if: inputs.scan-type == 'image'
+      uses: docker/build-push-action@v4
+      with:
+        context: ${{ inputs.path }}
+        push: false
+        tags: security-scan-image
+        secrets: ${{ secrets.DOCKER_IMAGE_SECRETS }}
+
+    - name: scan for full report (image)
+      if: inputs.scan-type == 'image'
+      run: trivy image security-scan-image --exit-code 0 --skip-db-update --scanners vuln --timeout 10m --list-all-pkgs
+
+    - name: scan with configured severities (config)
+      if: inputs.scan-type == 'config'
+      id: scan-config
       continue-on-error: true
-      id: scan
       env:
-        REPORT: ${{ inputs.use-test-reporter == true && '-f json -o ./scan-results/trivy.json' || '' }}
+        REPORT: ${{ inputs.use-test-reporter && '-f json -o ./scan-results/trivy.json' || '' }}
+        IGNOREFILE: ${{ inputs.trivyignorefile != '' && format('--ignorefile {0}', inputs.trivyignorefile) || '' }}
+      run: |
+        trivy config ${{ inputs.path }} \
+          --exit-code 1 \
+          --severity HIGH,CRITICAL,UNKNOWN \
+          --timeout 10m \
+          $IGNOREFILE \
+          $REPORT
+
+    - name: scan with configured severities (filesystem)
+      if: inputs.scan-type == 'filesystem'
+      id: scan-filesystem
+      continue-on-error: true
+      env:
+        REPORT: ${{ inputs.use-test-reporter && '-f json -o ./scan-results/trivy.json' || '' }}
         IGNOREFILE: ${{ inputs.trivyignorefile != '' && format('--ignorefile {0}', inputs.trivyignorefile) || '' }}
       run: |
         trivy fs ${{ inputs.path }} \
@@ -188,103 +144,13 @@ jobs:
           $IGNOREFILE \
           $REPORT
 
-    - name: Publish Test Report
-      if: ${{ always() && inputs.use-test-reporter }} 
-      uses: ctrf-io/github-test-reporter@v1
-      with:
-        report-path: './scan-results/trivy.ctrf.json'
-        template-path: '_security-tools/security-scanning/config_scan_template.hbs'
-        custom-report: true
-
-  image_scan:
-    if: ${{ inputs.scan-type == 'image' }}
-    outputs:
-      NOTIFICATION: ${{ steps.scan.outcome == 'failure' && 'true' || 'false' }}
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: checkout repository
-      uses: actions/checkout@v4 
-
-    - name: checkout security-scanning scripts
-      uses: actions/checkout@v4
-      with:
-        repository: zweitag/github-actions
-        ref: chore--create-configurable-Security-Scan
-        path: _security-tools
-        sparse-checkout: security-scanning
-
-    - name: create output folder
-      run: mkdir -p ./scan-results
-
-    - name: setup trivy
-      uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
-
-    - name: download vulnerabilities database from aws
-      continue-on-error: true
-      run: |
-        MAX_RETRIES=3
-        RETRY_DELAY=60
-        ATTEMPT=1
-        
-        until [ $ATTEMPT -gt $MAX_RETRIES ]
-        do
-          echo "Attempt $ATTEMPT of $MAX_RETRIES..."
-          GITHUB_TOKEN=${{ secrets.GH_TOKEN }} trivy fs --download-db-only --db-repository "${{ env.TRIVY_DB_REPOSITORY }}"
-
-          if [ $? -eq 0 ]; then
-            echo "Trivy DB download succeeded."
-            exit 0
-          else
-            echo "Trivy DB download failed. Retrying in $RETRY_DELAY seconds..."
-            ATTEMPT=$((ATTEMPT + 1))
-            sleep $RETRY_DELAY
-          fi
-        done
-        exit 1
-
-    - name: download vulnerabilities database if aws failed
-      if: failure()
-      run: |
-        MAX_RETRIES=3
-        RETRY_DELAY=60
-        ATTEMPT=1
-        
-        until [ $ATTEMPT -gt $MAX_RETRIES ]
-        do
-          echo "Attempt $ATTEMPT of $MAX_RETRIES..."
-          GITHUB_TOKEN=${{ secrets.GH_TOKEN }} trivy fs --download-db-only
-
-          if [ $? -eq 0 ]; then
-            echo "Trivy DB download succeeded."
-            exit 0
-          else
-            echo "Trivy DB download failed. Retrying in $RETRY_DELAY seconds..."
-            ATTEMPT=$((ATTEMPT + 1))
-            sleep $RETRY_DELAY
-          fi
-        done
-        exit 1
-
-    - name: build docker image
-      uses: docker/build-push-action@v4
-      with:
-        context: ${{ inputs.path }}
-        push: false
-        tags: security-scan-image
-        secrets: ${{ secrets.DOCKER_IMAGE_SECRETS }}
-
-    - name: scan image for full report
-      run: |
-        trivy image security-scan-image --exit-code 0 --skip-db-update --scanners vuln --timeout 10m --list-all-pkgs
-      
-    - name: scan docker image for configured severities
-      if: always()
+    - name: scan with configured severities (image)
+      if: inputs.scan-type == 'image'
+      id: scan-image
       continue-on-error: true
       env:
-        REPORT: ${{ inputs.use-test-reporter == true && '-f json -o ./scan-results/trivy.json' || '' }}
+        REPORT: ${{ inputs.use-test-reporter && '-f json -o ./scan-results/trivy.json' || '' }}
         IGNOREFILE: ${{ inputs.trivyignorefile != '' && format('--ignorefile {0}', inputs.trivyignorefile) || '' }}
-      id: scan
       run: |
         trivy image security-scan-image \
           --exit-code 1 \
@@ -295,27 +161,46 @@ jobs:
           $IGNOREFILE \
           $REPORT
 
-    - name: convert Trivy report to CTRF format
-      if: ${{ always() && inputs.use-test-reporter }}
+    - name: set scan outcome
+      id: scan
+      if: always()
       run: |
-        python3 _security-tools/security-scanning/trivyimage2ctrf.py ./scan-results/trivy.json ./scan-results/trivy.ctrf.json
+        if [[ "${{ steps.scan-config.outcome }}" == "failure" ]] || \
+           [[ "${{ steps.scan-filesystem.outcome }}" == "failure" ]] || \
+           [[ "${{ steps.scan-image.outcome }}" == "failure" ]]; then
+          echo "outcome=failure" >> $GITHUB_OUTPUT
+          exit 1
+        fi
+
+    - name: convert Trivy report to CTRF format (config)
+      if: always() && inputs.use-test-reporter && inputs.scan-type == 'config'
+      run: |
+        python3 _security-tools/security-scanning/trivyconfig2ctrf.py \
+          ./scan-results/trivy.json \
+          ./scan-results/trivy.ctrf.json
+
+    - name: convert Trivy report to CTRF format (image)
+      if: ${{ always() && inputs.use-test-reporter && inputs.scan-type == 'image' }}
+      run: |
+        python3 _security-tools/security-scanning/trivyimage2ctrf.py \
+          ./scan-results/trivy.json \
+          ./scan-results/trivy.ctrf.json
 
     - name: Publish Test Report
-      uses: ctrf-io/github-test-reporter@v1
       if: ${{ always() && inputs.use-test-reporter }}
+      uses: ctrf-io/github-test-reporter@v1
       with:
         report-path: './scan-results/trivy.ctrf.json'
-        template-path: '_security-tools/security-scanning/image_scan_template.hbs'
+        template-path: '_security-tools/security-scanning/${{ inputs.scan-type == "image" && "image_scan_template.hbs" || "config_scan_template.hbs" }}'
         custom-report: true
 
-  create_issues:
-    needs: [configuration_scan, filesystem_scan, image_scan]
+  create_issue:
+    needs: [security_scan]
     runs-on: ubuntu-latest
-    if: ${{ inputs.issue-on-findings != 'false' }}
+    if: ${{ always() && inputs.issue-on-findings != '' && needs.security_scan.outputs.NOTIFICATION == 'true' }}
 
     steps:
       - name: Create issue/Comment on issue
-        if: ${{ always() && (needs.image_scan.outputs.NOTIFICATION == 'true' || needs.configuration_scan.outputs.NOTIFICATION == 'true' || needs.filesystem_scan.outputs.NOTIFICATION == 'true') }}
         uses: actions/github-script@v7
         with:
           script: |
